CREATE TABLE IF NOT EXISTS customer(
CUSTOMER_ID INT NOT NULL,
CUSTOMER_NAME VARCHAR(20) NOT NULL,
CUSTOMER_PHONE VARCHAR(10) NOT NULL,
CUSTOMER_CITY varchar(30) NOT NULL,
CUSTOMER_GENDER CHAR,
PRIMARY KEY (CUSTOMER_ID));