CREATE TABLE IF NOT EXISTS supplier_pricing (
PRICING_ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
SUPPLIER_ID INT NOT NULL,
SUPPLIER_PRICE INT DEFAULT 0,
PRIMARY KEY (PRICING_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES product (PRODUCT_ID),
FOREIGN KEY (SUPPLIER_ID) REFERENCES supplier (SUPPLIER_ID)
);