CREATE TABLE IF NOT EXISTS product (
PRODUCT_ID INT NOT NULL,
PRODUCT_NAME VARCHAR(20) NOT NULL DEFAULT "Dummy",
PRODUCT_DESC VARCHAR(60),
CATEGORY_ID INT NOT NULL,
PRIMARY KEY (PRODUCT_ID),
FOREIGN KEY (CATEGORY_ID) REFERENCES category (CATEGORY_ID)
);